create table BORROW(
   LOANNO INT,
   CNAME VARCHAR(50),   BNAME VARCHAR(50),   AMOUNT DECIMAL(8,2),
)
insert into BORROW(LOANNO,CNAME,BNAME,AMOUNT)
values(201,' ANIL',' VRCE ',1000.00)

insert into BORROW(LOANNO,CNAME,BNAME,AMOUNT)
values(206 ,'MEHUL',' AJNI', 5000.00 )

insert into BORROW(LOANNO,CNAME,BNAME,AMOUNT)
values(311, 'SUNIL',' DHARAMPETH', 3000.00)

insert into BORROW(LOANNO,CNAME,BNAME,AMOUNT)
values(321 ,'MADHURI','ANDHERI', 2000.00)

insert into BORROW(LOANNO,CNAME,BNAME,AMOUNT)
values(375 ,'PRAMOD',' VIRAR', 8000.00 )

insert into BORROW(LOANNO,CNAME,BNAME,AMOUNT)
values(481,' KRANTI',' NEHRU PLACE', 3000.00)

drop table borrow